### ISSUE TITLE
[Twellve - Menu] 비쥬얼 메뉴와 비저블 메뉴 컴포넌트 설계

### ISSUE THREAD

**Issue by MyoungHwaShin** [twelive/final-project#10]
# 😎 이슈 내용
- [x] 모바일 /랩탑/ 데스크탑 동일 스타일 비저블 메뉴

# :fire: 수정 사항

## 📸 레퍼런스

<비저블 메뉴>
 
랩탑/ 데스크탑 

<img width="279" alt="image" src="https://github.com/twelive/final-project/assets/73214037/78f43900-ece1-45f4-a053-68ffda277620">

**Comment by seojinman** [comment]
비저블 메뉴바 완성
![image](https://github.com/twelive/final-project/assets/117728530/ac625899-6c51-4fd7-81da-e2c94a7400d6)

**Comment by uniS2** [comment]
현재 작업 종료 확인되어 이슈 종료합니다.
추가 작업은 새로 이슈 작성해주세요 :) 수고하셨습니다!
