### ISSUE TITLE
[Twellve - Main]  메인 페이지 

### ISSUE THREAD

**Issue by MyoungHwaShin** [twelive/final-project#11]
# 😎 이슈 내용
- [x]  fetch data 작업
- [x]  grid를 이용한 스타일링
- [x]  반응형 구현 완료

# :fire: 수정 사항

## 📸 레퍼런스

모바일

<img width="233" alt="image" src="https://github.com/twelive/final-project/assets/73214037/7579849f-c006-4748-b18a-8197c402a45c">

랩탑

<img width="490" alt="image" src="https://github.com/twelive/final-project/assets/73214037/0f0819a6-4778-4faf-9684-5fcfc9d22a6c">

데스크탑

<img width="1440" alt="image" src="https://github.com/twelive/final-project/assets/73214037/047b9123-82ee-46c2-ba47-3d60ed9ba1fc">

**Comment by uniS2** [comment]
작업 완료 확인되어서 이슈 종료하겠습니다.
추가 애니메이션 관련 이슈 생성하겠습니다.
