### ISSUE TITLE
[Twellve - Detail] 해당 영상 디테일 페이지 

### ISSUE THREAD

**Issue by MyoungHwaShin** [twelive/final-project#12]
# 😎 이슈 내용
- [x] 클릭한 해당 영상 정보 Data fetch 작업
- [x] 메인(비디오 상단), 관련콘텐츠(서브 하단) 으로 나누어 렌더링 작업
- [ ] 영상 정보 내 더보기/간략히 버튼
- [ ] 모바일, 랩탑 시안 작업 마무리

# :fire: 수정 사항

## 📸 레퍼런스

모바일

<img width="343" alt="image" src="https://github.com/twelive/final-project/assets/73214037/393ed130-28c1-406c-94fd-688ecfdb4b06">

랩탑

<img width="490" alt="image" src="https://github.com/twelive/final-project/assets/73214037/3a814f2a-7c90-4804-b7e4-9d984bfa94ff">

데스크탑

<img width="1440" alt="image" src="https://github.com/twelive/final-project/assets/73214037/5fa4c918-5565-4e57-acd8-90e35480916e">

**Comment by uniS2** [comment]
기본 작업 완료하여 상세페이지 관련 추가 작업 진행하겠습니다.
