### ISSUE TITLE
[Twellve - Discussion] 리액트 컴포넌트의 반응형을 위한 useMediaQuery hooks 설치

### ISSUE THREAD

**Issue by MyoungHwaShin** [twelive/final-project#14]
# 😎 이슈 내용

동일 컴포넌트의 사이즈별 디자인 및 컨텐츠 변동으로 인해 hooks 설치가 필요해 보입니다. 다른 방법 아시나요 ?

https://velog.io/@st2702/%EB%B0%98%EC%9D%91%ED%98%95-%EC%9B%B9-Media-Query

# :fire: 수정 사항

## 📸 레퍼런스

<img width="493" alt="image" src="https://github.com/twelive/final-project/assets/73214037/e76e4db2-6fb1-47c0-b199-7ea235995616">

<img width="294" alt="image" src="https://github.com/twelive/final-project/assets/73214037/4eb83744-641b-4dee-bbac-ef3244ba3942">

**Comment by uniS2** [comment]
현재 CSS 작업용 중단점만 `ThemeProvider` 정해져 있기 때문에 명화님이 말씀하신대로 해당 훅을 사용하는게 더 효율적으로 보입니다!
useMediaQuery hooks 사용시 기존 테마 Provider도 필요하지 않을거같아서 반응형 작업 진행하면서 함께 검토해주시면 감사하겠습니다 👍
