### ISSUE TITLE
[Twellve - fetch Data] data fetch 통신

### ISSUE THREAD

**Issue by uniS2** [twelive/final-project#17]
# 😎 이슈 내용
- 데이터 로딩 과정 중 경로 문제로 인한 이슈 발생

# :fire: 수정 사항
- 경로 해결
- 기존 경로       `const response = await fetch('public/videos/popular.json');`
- 수정 경로      `const response = await fetch('/videos/popular.json');`

## ✨ 기대 결과
- 추후 `Axios` 변경 예정

## 📸 레퍼런스

https://velog.io/@daeun/React-public%ED%8F%B4%EB%8D%94-src%ED%8F%B4%EB%8D%94-%EC%96%B4%EB%94%94%EC%97%90-%EB%84%A3%EC%96%B4%EC%95%BC-%EB%90%98%EB%8A%94%EA%B1%B8%EA%B9%8C

**Comment by sy0725** [comment]
수정완료하였습니다 !!

**Comment by uniS2** [comment]
> 수정완료하였습니다 !!

수고하셨습니다 👍🏻
