### ISSUE TITLE
[Twellve - Nav/MenuBar] 클릭시 작동 오류 수정 

### ISSUE THREAD

**Issue by uniS2** [twelive/final-project#35]
# 😎 이슈 내용
- [x] Reducer 충돌로 인한 작동 오류

# :fire: 수정 사항

## ✨ 기대 결과
정상작동될 경우 네비게이션과 메뉴바 각각 작동 기대

**Comment by uniS2** [comment]
@seojinman 님 동작 충돌 오류 해결방안을 찾아 제안드립니다.
말씀하셨던 것처럼 네비바와 메뉴바에서 관리되고 있는 `navReducer`, `toggleReducer`을 포인트로 해결방안을 찾았습니다.

Redux는 여러 개의 리듀서를 결합시 단일 스토어(`@store/store`)를 사용하고 각 액션이 모든 리듀서에 전달되기 때문에, 액션 타입 충돌이 실제 발생한다고 합니다. 
![image](https://github.com/twelive/final-project/assets/134567469/645dbd0b-8748-45f5-84f9-797d06ebdaf1)
![image](https://github.com/twelive/final-project/assets/134567469/4f112619-d604-4eeb-ace4-35800068712b)

따라서, 여러 리듀서에서 동일한 액션 타입을 사용할시에, 동일한 액션을 처리하려 시도하였기 때문에 이로인해 예상치 못했던 네비바 작동시 메뉴바가 작동되는 현상이 도출되었음을 판단하였습니다.

해결방안으로 다음과 같은 과정을 제시합니다.
정상작동 검토한 후 로직 정리하여 작업 완료해주세요.
아울러 Reducer 간에 충돌이 더 발생하지 않도록 주말 내에 액션명 정리하겠습니다.
오늘 고생하셨습니다 :)
1. navReducer 내 타입 `NAV_CLICK`으로 변경
2. toggleReducer 내 타입 `TOGGLE_CLICK`으로 변경
3. reducer 선언 파일 내 `NavAction`과 `ToggleAction` type 변경
4. NavButton 컴포넌트 dispatch 타입 `NAV_CLICK`으로 수정
5. Header와 MenuBar 컴포넌트 `TOGGLE_CLICK`으로 수정

---
*아울러 현재 Header 컴포넌트와 MenuBar 컴포넌트에 걸린 handleToggle 로직이 동일하므로 추후 리팩토링시 훅으로 생성해도 좋을거같습니다 !

**Comment by seojinman** [comment]
감사합니다 소이님 글을 자세하게 작성해 주신 덕분에 잘 해결할 수 있었습니다.  문제를 해결하여 Pull requests했습니다 .
