### ISSUE TITLE
[Twellve - Header] 리스트 글씨가 헤더의 위로 올라오는 버그 

### ISSUE THREAD

**Issue by MyoungHwaShin** [twelive/final-project#45]
# 😎 이슈 내용
- [x] 리스트 글씨가 헤더의 위로 올라오는 버그 

# :fire: 수정 사항

https://github.com/twelive/final-project/assets/73214037/c49f01c4-6d0d-4cde-8971-d2485798eca7

**Comment by uniS2** [comment]
명화님 헤더 확인해보니까 z-index 값 설정해서 화면 맨 위로 올라오면 해결됩니다!
헤더가 리스트를 가리는건 내일 회의해서 mainPage 컴포넌트 내 margin을 주거나 flex로 배치하는 등 논의해봐요. 주말인데 고생하셨습니다 :)
